- hosts: all
  become: true
  roles:
    - common

- hosts: 10.101.53.202
  become: true
  roles:
    - frontend

- hosts: 10.101.53.201
  become: true
  roles:
    - backend

# Exemples:
# - hosts: address_ip_front_1
#   become: true
#   roles:
#     - frontend
#
# - hosts: address_ip_front_2
#   become: true
#   roles:
#     - frontend
