#- name: "Check update"
  #  shell: yum check-update warn=false

- name: "Cloner le dossier backend_student sur la machine"
  become: false
  shell: git clone https://github.com/assimatagba/tnsa-810-backend.git

- name: "Commenter la ligne mysql_user dans docker-compose.yml"
  lineinfile:
    path: tnsa-810-backend/docker-compose.yml
    regexp: '^      MYSQL_USER'
    line: '      #MYSQL_USER: root'

- name: "Installer les dépendances nécessaire du backend"
  shell: cd tnsa-810-backend && yarn install

- name: "Build le backend sur docker"
  shell: cd tnsa-810-backend && docker-compose build

- name: "Lancer le backend sur docker"
  shell: cd tnsa-810-backend && docker-compose up -d
